from pathlib import Path
path = Path("src/components/TypeAnswer.tsx")
text = path.read_text(encoding="utf-8")
old = """      <div className=\"type-input-row\">\n        <input\n          className=\"type-input\"\n          value={value}\n          onChange={(e) => setValue(e.target.value)}\n          onKeyDown={enterPress}\n          placeholder=\"Cevabini yaz...\"\n        />\n        <button className=\"btn btn-primary\" onClick={handleSubmit} disabled={loading || !value.trim()}>\n          {loading ? 'Kontrol ediliyor...' : 'Gonder'}\n        </button>\n      </div>\n      {result && (\n        <div className=\"type-result\">\n          <div className=\"type-score\">\n            Skor: <strong>{Math.round(result.score)}%</strong> {result.verdict !== 'exact' && `(${result.verdict})`}\n          </div>\n          {result.synonyms && result.synonyms.length > 0 && (\n            <div className=\"type-synonyms\">\n              Eþ anlamlýlar: {result.synonyms.slice(0, 5).join(', ')}\n            </div>\n          )}\n        </div>\n      )}"""
new = """      <div className=\"type-input-row\">\n        <input\n          className=\"type-input\"\n          value={value}\n          onChange={(e) => setValue(e.target.value)}\n          onKeyDown={enterPress}\n          placeholder=\"Cevabini yaz...\"\n        />\n        <button className=\"btn btn-primary\" onClick={handleSubmit} disabled={loading || !value.trim()}>\n          {loading ? 'Kontrol ediliyor...' : 'Gonder'}\n        </button>\n      </div>\n      {result && (\n        <div className=\"type-result\">\n          <div className=\"type-score\">\n            Skor: <strong>{Math.round(result.score)}%</strong> {result.verdict !== 'exact' && `(${result.verdict})`}\n          </div>\n          <div style={{ marginTop: 4 }}><span>Doðru cevap:</span> <strong>{correctAnswer}</strong></div>\n          <div style={{ display: 'flex', gap: 10, marginTop: 8, alignItems: 'center', flexWrap: 'wrap' }}>\n            <button\n              className=\"btn btn-outline btn-sm\"\n              onClick={() => setShowSynonyms((v) => !v)}\n              disabled={!result.synonyms || result.synonyms.length === 0}\n            >\n              Ýpucu (eþ anlamlýlar)\n            </button>\n            <button\n              className=\"btn btn-secondary btn-sm\"\n              onClick={() => onAnswer(false, question.word, value.trim(), direction === 'tr-to-en' ? 'tr-to-en' : 'en-to-tr')}\n            >\n              Bilmiyorum / Geç\n            </button>\n          </div>\n          {showSynonyms && result.synonyms && result.synonyms.length > 0 && (\n            <div className=\"type-synonyms\">\n              Eþ anlamlýlar: {result.synonyms.slice(0, 5).join(', ')}\n            </div>\n          )}\n        </div>\n      )}\n      {!result && (\n        <div style={{ display: 'flex', gap: 10, marginTop: 6 }}>\n          <button\n            className=\"btn btn-secondary btn-sm\"\n            onClick={() => {\n              setValue('');\n              onAnswer(false, question.word, '', direction === 'tr-to-en' ? 'tr-to-en' : 'en-to-tr');\n            }}\n          >\n            Bilmiyorum / Geç\n          </button>\n        </div>\n      )}"""
if old not in text:
    raise SystemExit('old not found')
text = text.replace(old, new)
path.write_text(text, encoding="utf-8")
